# Introduction

In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
a = np.arange(24).reshape((2,3,4))
print(a.__str__())
print("\nDimensions: ", a.ndim)
print("Shape: ", a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Dimensions:  3
Shape:  (2, 3, 4)


In [19]:
a.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [28]:
a = np.arange(12).reshape((3,4))
print(a.__str__())
print("\nDimensions: ", a.ndim)
print("Shape: ", a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Dimensions:  2
Shape:  (3, 4)


In [21]:
a.sum(axis=1)

array([ 6, 22, 38])

In [29]:
a = np.flip(a, axis=1)
print(a.__str__())
print("\nDimensions: ", a.ndim)
print("Shape: ", a.shape)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]

Dimensions:  2
Shape:  (3, 4)
